# Site configuration
title: Nic Grayson
description: >-
  Nic Grayson is an infrastructure engineer. Notes on the command line and
  other things that make computers behave.
url: https://nicgrayson.com
lang: en

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true

# Site owner
owner:
  name: Nic Grayson
  email: me@nicgrayson.com
  github: nicgrayson

# Files to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
